print("\n---------------------------------------------------------------------------")

print("\nPROGRAMA QUE CONVERTE TEMPERATURA EM GRAUS CELSIUS PARA GRAUS FAHRNHEIT\n")



#Dados
grau_celsius = eval(input("Por favor informe uma temperatura em graus celsius:"))
grau_fahrenheit = 0




print("\nTemperatura em graus celsius:",grau_celsius)



#Processamento 
grau_fahrenheit = (grau_celsius * 1.8) + 32

#Resposta

print("Temperatura em graus Fahrenheit:", grau_fahrenheit)

print("\n---------------------------------------------------------------------------")

